[server]
headless = true
enableCORS = false
enableXsrfProtection = false
fileWatcherType = "none"
maxUploadSize = 1024

[browser]
gatherUsageStats = false

[theme]
base = "light"
primaryColor = "#0b6e69"
